const palabrasClave = [
    '18',
    'Domicilio',
    'Con lugar',
    'Gordibuena',
    'Madura',
    'Señora',
    'Económico',
    'Anal',
    'Salida san luis',
    'Gordita',
    'Gratis',
    'Maduras',
    'Whatsapp',
    'Independiente',
    'Sexo anal',
    'Nalgona',
    'Chaparrita',
    'Milf',
    'Scorts',
    'Madurita',
    'Chichona',
    'Delgada',
    'Tetona',
    'Flaquita',
    'Oriente',
    'Morena',
    'Lugar',
    'Embarazada',
    'Oral',
    'Compañía',
    'Telegram',
    'Colombiana',
    'Mañana',
    '2 horas',
    'Garantizadas',
    'Cachonda',
    'Palo alto',
    'Fotos',
    'Oral mutuo',
    'Ninfómana'
];

export default palabrasClave;
